name: Bug report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please provide a Minimal Reproducible Example and share any additional information that may help reproduce, troubleshoot, and hopefully fix the issue, including screenshots.
  - type: textarea
    attributes:
      label: Describe the issue
      description: A concise description of the issue and how we can reproduce it.
      placeholder: Describe the issue step by step
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: Environment information where the problem occurs.
      value: |
        - LMS Version: develop
    validations:
      required: false
labels:
  - bug
  - area/client
  - area/server
